const img = (seed, w = 400, h = 300) =>
  `https://picsum.photos/seed/${seed}/${w}/${h}`;

export const fruits = [
  { id: "f1",  name: "Red Apple",            price: 1.49, unit: "each",    image: img("apple1") },
  { id: "f2",  name: "Green Apple",           price: 1.39, unit: "each",    image: img("apple2") },
  { id: "f3",  name: "Gala Apple",            price: 1.59, unit: "each",    image: img("apple3") },
  { id: "f4",  name: "Fuji Apple",            price: 1.69, unit: "each",    image: img("apple4") },
  { id: "f5",  name: "Banana (bunch)",        price: 1.29, unit: "bunch",   image: img("banana1") },
  { id: "f6",  name: "Plantain",              price: 0.89, unit: "each",    image: img("plantain1") },
  { id: "f7",  name: "Navel Orange",          price: 1.19, unit: "each",    image: img("orange1") },
  { id: "f8",  name: "Blood Orange",          price: 1.49, unit: "each",    image: img("orange2") },
  { id: "f9",  name: "Mandarin Clementine",   price: 3.99, unit: "bag",     image: img("mand1") },
  { id: "f10", name: "Pink Grapefruit",       price: 1.79, unit: "each",    image: img("gfruit1") },
  { id: "f11", name: "Strawberries",          price: 3.49, unit: "pint",    image: img("straw1") },
  { id: "f12", name: "Blueberries",           price: 4.29, unit: "pint",    image: img("blue1") },
  { id: "f13", name: "Raspberries",           price: 3.99, unit: "pint",    image: img("rasp1") },
  { id: "f14", name: "Blackberries",          price: 4.49, unit: "pint",    image: img("black1") },
  { id: "f15", name: "Watermelon",            price: 6.99, unit: "whole",   image: img("water1") },
  { id: "f16", name: "Cantaloupe",            price: 3.49, unit: "whole",   image: img("canta1") },
  { id: "f17", name: "Honeydew Melon",        price: 3.99, unit: "whole",   image: img("honey1") },
  { id: "f18", name: "Seedless Grapes (Red)", price: 3.99, unit: "lb",      image: img("grape1") },
  { id: "f19", name: "Green Grapes",          price: 3.79, unit: "lb",      image: img("grape2") },
  { id: "f20", name: "Peach",                 price: 1.29, unit: "each",    image: img("peach1") },
  { id: "f21", name: "Nectarine",             price: 1.39, unit: "each",    image: img("nectar1") },
  { id: "f22", name: "Plum",                  price: 0.99, unit: "each",    image: img("plum1") },
  { id: "f23", name: "Apricot",               price: 0.89, unit: "each",    image: img("apri1") },
  { id: "f24", name: "Pineapple",             price: 2.99, unit: "whole",   image: img("pine1") },
  { id: "f25", name: "Mango (Ataulfo)",       price: 1.49, unit: "each",    image: img("mango1") },
  { id: "f26", name: "Mango (Tommy)",         price: 1.79, unit: "each",    image: img("mango2") },
  { id: "f27", name: "Papaya",                price: 2.49, unit: "each",    image: img("papaya1") },
  { id: "f28", name: "Kiwi",                  price: 0.79, unit: "each",    image: img("kiwi1") },
  { id: "f29", name: "Star Fruit",            price: 1.99, unit: "each",    image: img("star1") },
  { id: "f30", name: "Dragon Fruit",          price: 4.99, unit: "each",    image: img("dragon1") },
  { id: "f31", name: "Passion Fruit",         price: 1.29, unit: "each",    image: img("passion1") },
  { id: "f32", name: "Guava",                 price: 0.99, unit: "each",    image: img("guava1") },
  { id: "f33", name: "Lychee",               price: 3.99, unit: "bag",     image: img("lychee1") },
  { id: "f34", name: "Pomegranate",           price: 2.99, unit: "each",    image: img("pome1") },
  { id: "f35", name: "Lemon",                 price: 0.69, unit: "each",    image: img("lemon1") },
  { id: "f36", name: "Lime",                  price: 0.59, unit: "each",    image: img("lime1") },
  { id: "f37", name: "Avocado (Hass)",        price: 1.49, unit: "each",    image: img("avoc1") },
  { id: "f38", name: "Coconut",               price: 2.49, unit: "each",    image: img("coco1") },
  { id: "f39", name: "Fig",                   price: 0.99, unit: "each",    image: img("fig1") },
  { id: "f40", name: "Dates (Medjool)",       price: 6.99, unit: "bag",     image: img("date1") },
  { id: "f41", name: "Pear (Bartlett)",       price: 1.29, unit: "each",    image: img("pear1") },
  { id: "f42", name: "Asian Pear",            price: 1.99, unit: "each",    image: img("pear2") },
];
export const vegetables = [
  { id: "v1",  name: "Broccoli Crown",        price: 2.49, unit: "each",    image: img("broc1") },
  { id: "v2",  name: "Cauliflower",           price: 2.99, unit: "each",    image: img("cauli1") },
  { id: "v3",  name: "Romanesco",             price: 3.49, unit: "each",    image: img("roman1") },
  { id: "v4",  name: "Spinach (baby)",        price: 3.29, unit: "5 oz",    image: img("spin1") },
  { id: "v5",  name: "Kale (curly)",          price: 2.49, unit: "bunch",   image: img("kale1") },
  { id: "v6",  name: "Lacinato Kale",         price: 2.79, unit: "bunch",   image: img("kale2") },
  { id: "v7",  name: "Swiss Chard",           price: 2.29, unit: "bunch",   image: img("chard1") },
  { id: "v8",  name: "Arugula",               price: 3.49, unit: "5 oz",    image: img("arug1") },
  { id: "v9",  name: "Romaine Lettuce",       price: 1.99, unit: "each",    image: img("rom1") },
  { id: "v10", name: "Iceberg Lettuce",       price: 1.49, unit: "each",    image: img("ice1") },
  { id: "v11", name: "Butter Lettuce",        price: 2.49, unit: "each",    image: img("butt1") },
  { id: "v12", name: "Celery",                price: 1.99, unit: "bunch",   image: img("celery1") },
  { id: "v13", name: "Carrot (bunch)",        price: 1.79, unit: "bunch",   image: img("carr1") },
  { id: "v14", name: "Baby Carrots",          price: 2.29, unit: "bag",     image: img("bcarr1") },
  { id: "v15", name: "Yellow Onion",          price: 0.99, unit: "each",    image: img("onion1") },
  { id: "v16", name: "Red Onion",             price: 1.19, unit: "each",    image: img("onion2") },
  { id: "v17", name: "Green Onion",           price: 0.99, unit: "bunch",   image: img("gonion1") },
  { id: "v18", name: "Garlic (head)",         price: 0.79, unit: "each",    image: img("garlic1") },
  { id: "v19", name: "Shallot",               price: 0.99, unit: "each",    image: img("shall1") },
  { id: "v20", name: "Russet Potato",         price: 0.99, unit: "each",    image: img("pot1") },
  { id: "v21", name: "Yukon Gold Potato",     price: 3.99, unit: "bag",     image: img("pot2") },
  { id: "v22", name: "Sweet Potato",          price: 1.29, unit: "each",    image: img("spot1") },
  { id: "v23", name: "Purple Potato",         price: 2.99, unit: "bag",     image: img("ppot1") },
  { id: "v24", name: "Zucchini",              price: 1.49, unit: "each",    image: img("zuc1") },
  { id: "v25", name: "Yellow Squash",         price: 1.49, unit: "each",    image: img("ysq1") },
  { id: "v26", name: "Butternut Squash",      price: 2.99, unit: "each",    image: img("bsq1") },
  { id: "v27", name: "Acorn Squash",          price: 2.49, unit: "each",    image: img("asq1") },
  { id: "v28", name: "Bell Pepper (Red)",     price: 1.79, unit: "each",    image: img("pep1") },
  { id: "v29", name: "Bell Pepper (Green)",   price: 1.29, unit: "each",    image: img("pep2") },
  { id: "v30", name: "Bell Pepper (Yellow)",  price: 1.79, unit: "each",    image: img("pep3") },
  { id: "v31", name: "Jalapeño",              price: 0.49, unit: "each",    image: img("jal1") },
  { id: "v32", name: "Habanero",              price: 0.59, unit: "each",    image: img("hab1") },
  { id: "v33", name: "Serrano Pepper",        price: 0.39, unit: "each",    image: img("serr1") },
  { id: "v34", name: "Tomato (Roma)",         price: 0.99, unit: "each",    image: img("tom1") },
  { id: "v35", name: "Cherry Tomatoes",       price: 3.49, unit: "pint",    image: img("ctom1") },
  { id: "v36", name: "Heirloom Tomatoes",     price: 4.99, unit: "lb",      image: img("htom1") },
  { id: "v37", name: "Cucumber",              price: 1.29, unit: "each",    image: img("cuc1") },
  { id: "v38", name: "English Cucumber",      price: 1.99, unit: "each",    image: img("ecuc1") },
  { id: "v39", name: "Asparagus",             price: 3.99, unit: "bunch",   image: img("asp1") },
  { id: "v40", name: "Green Beans",           price: 2.99, unit: "bag",     image: img("gb1") },
  { id: "v41", name: "Sugar Snap Peas",       price: 3.49, unit: "bag",     image: img("pea1") },
  { id: "v42", name: "Edamame",               price: 2.99, unit: "bag",     image: img("edm1") },
  { id: "v43", name: "Corn on the Cob",       price: 0.79, unit: "each",    image: img("corn1") },
  { id: "v44", name: "Mushrooms (Baby Bella)", price: 3.49, unit: "8 oz",   image: img("mush1") },
];
export const vegetables = [
  { id: "v1",  name: "Broccoli Crown",        price: 2.49, unit: "each",    image: img("broc1") },
  { id: "v2",  name: "Cauliflower",           price: 2.99, unit: "each",    image: img("cauli1") },
  { id: "v3",  name: "Romanesco",             price: 3.49, unit: "each",    image: img("roman1") },
  { id: "v4",  name: "Spinach (baby)",        price: 3.29, unit: "5 oz",    image: img("spin1") },
  { id: "v5",  name: "Kale (curly)",          price: 2.49, unit: "bunch",   image: img("kale1") },
  { id: "v6",  name: "Lacinato Kale",         price: 2.79, unit: "bunch",   image: img("kale2") },
  { id: "v7",  name: "Swiss Chard",           price: 2.29, unit: "bunch",   image: img("chard1") },
  { id: "v8",  name: "Arugula",               price: 3.49, unit: "5 oz",    image: img("arug1") },
  { id: "v9",  name: "Romaine Lettuce",       price: 1.99, unit: "each",    image: img("rom1") },
  { id: "v10", name: "Iceberg Lettuce",       price: 1.49, unit: "each",    image: img("ice1") },
  { id: "v11", name: "Butter Lettuce",        price: 2.49, unit: "each",    image: img("butt1") },
  { id: "v12", name: "Celery",                price: 1.99, unit: "bunch",   image: img("celery1") },
  { id: "v13", name: "Carrot (bunch)",        price: 1.79, unit: "bunch",   image: img("carr1") },
  { id: "v14", name: "Baby Carrots",          price: 2.29, unit: "bag",     image: img("bcarr1") },
  { id: "v15", name: "Yellow Onion",          price: 0.99, unit: "each",    image: img("onion1") },
  { id: "v16", name: "Red Onion",             price: 1.19, unit: "each",    image: img("onion2") },
  { id: "v17", name: "Green Onion",           price: 0.99, unit: "bunch",   image: img("gonion1") },
  { id: "v18", name: "Garlic (head)",         price: 0.79, unit: "each",    image: img("garlic1") },
  { id: "v19", name: "Shallot",               price: 0.99, unit: "each",    image: img("shall1") },
  { id: "v20", name: "Russet Potato",         price: 0.99, unit: "each",    image: img("pot1") },
  { id: "v21", name: "Yukon Gold Potato",     price: 3.99, unit: "bag",     image: img("pot2") },
  { id: "v22", name: "Sweet Potato",          price: 1.29, unit: "each",    image: img("spot1") },
  { id: "v23", name: "Purple Potato",         price: 2.99, unit: "bag",     image: img("ppot1") },
  { id: "v24", name: "Zucchini",              price: 1.49, unit: "each",    image: img("zuc1") },
  { id: "v25", name: "Yellow Squash",         price: 1.49, unit: "each",    image: img("ysq1") },
  { id: "v26", name: "Butternut Squash",      price: 2.99, unit: "each",    image: img("bsq1") },
  { id: "v27", name: "Acorn Squash",          price: 2.49, unit: "each",    image: img("asq1") },
  { id: "v28", name: "Bell Pepper (Red)",     price: 1.79, unit: "each",    image: img("pep1") },
  { id: "v29", name: "Bell Pepper (Green)",   price: 1.29, unit: "each",    image: img("pep2") },
  { id: "v30", name: "Bell Pepper (Yellow)",  price: 1.79, unit: "each",    image: img("pep3") },
  { id: "v31", name: "Jalapeño",              price: 0.49, unit: "each",    image: img("jal1") },
  { id: "v32", name: "Habanero",              price: 0.59, unit: "each",    image: img("hab1") },
  { id: "v33", name: "Serrano Pepper",        price: 0.39, unit: "each",    image: img("serr1") },
  { id: "v34", name: "Tomato (Roma)",         price: 0.99, unit: "each",    image: img("tom1") },
  { id: "v35", name: "Cherry Tomatoes",       price: 3.49, unit: "pint",    image: img("ctom1") },
  { id: "v36", name: "Heirloom Tomatoes",     price: 4.99, unit: "lb",      image: img("htom1") },
  { id: "v37", name: "Cucumber",              price: 1.29, unit: "each",    image: img("cuc1") },
  { id: "v38", name: "English Cucumber",      price: 1.99, unit: "each",    image: img("ecuc1") },
  { id: "v39", name: "Asparagus",             price: 3.99, unit: "bunch",   image: img("asp1") },
  { id: "v40", name: "Green Beans",           price: 2.99, unit: "bag",     image: img("gb1") },
  { id: "v41", name: "Sugar Snap Peas",       price: 3.49, unit: "bag",     image: img("pea1") },
  { id: "v42", name: "Edamame",               price: 2.99, unit: "bag",     image: img("edm1") },
  { id: "v43", name: "Corn on the Cob",       price: 0.79, unit: "each",    image: img("corn1") },
  { id: "v44", name: "Mushrooms (Baby Bella)", price: 3.49, unit: "8 oz",   image: img("mush1") },
];
export const snacks = [
  { id: "s1",  name: "Lay's Classic Chips",         price: 4.49, unit: "bag",  image: img("chips1") },
  { id: "s2",  name: "Doritos Nacho Cheese",        price: 4.99, unit: "bag",  image: img("dor1") },
  { id: "s3",  name: "Pringles Original",           price: 2.99, unit: "can",  image: img("pring1") },
  { id: "s4",  name: "Pringles Sour Cream",         price: 2.99, unit: "can",  image: img("pring2") },
  { id: "s5",  name: "Cheetos Crunchy",             price: 4.49, unit: "bag",  image: img("cheet1") },
  { id: "s6",  name: "Cheetos Puffs",               price: 4.49, unit: "bag",  image: img("cheet2") },
  { id: "s7",  name: "Fritos Original",             price: 3.99, unit: "bag",  image: img("frit1") },
  { id: "s8",  name: "Ruffles Cheddar",             price: 4.29, unit: "bag",  image: img("ruff1") },
  { id: "s9",  name: "Kettle Brand Sea Salt",       price: 4.99, unit: "bag",  image: img("kett1") },
  { id: "s10", name: "PopCorners Kettle Corn",      price: 4.79, unit: "bag",  image: img("popc1") },
  { id: "s11", name: "Skinny Pop Popcorn",          price: 5.49, unit: "bag",  image: img("skinny1") },
  { id: "s12", name: "Oreos Original",              price: 4.99, unit: "pack", image: img("oreo1") },
  { id: "s13", name: "Oreos Double Stuff",          price: 5.29, unit: "pack", image: img("oreo2") },
  { id: "s14", name: "Chips Ahoy! Chocolate Chip",  price: 4.49, unit: "pack", image: img("chip1") },
  { id: "s15", name: "Nutter Butter",               price: 4.29, unit: "pack", image: img("nutter1") },
  { id: "s16", name: "Rice Krispies Treats",        price: 3.99, unit: "pack", image: img("rice1") },
  { id: "s17", name: "Nature Valley Oats & Honey",  price: 5.49, unit: "box",  image: img("nv1") },
  { id: "s18", name: "Kind Dark Chocolate Bar",     price: 1.99, unit: "each", image: img("kind1") },
  { id: "s19", name: "Clif Bar Chocolate Chip",    price: 1.89, unit: "each", image: img("clif1") },
  { id: "s20", name: "RX Bar Blueberry",           price: 2.49, unit: "each", image: img("rx1") },
  { id: "s21", name: "Larabar Apple Pie",          price: 1.79, unit: "each", image: img("lara1") },
  { id: "s22", name: "Reese's Peanut Butter Cups", price: 1.99, unit: "pack", image: img("rees1") },
  { id: "s23", name: "Snickers Bar",               price: 1.79, unit: "each", image: img("snic1") },
  { id: "s24", name: "Kit Kat Bar",                price: 1.79, unit: "each", image: img("kk1") },
  { id: "s25", name: "M&M's Peanut",               price: 4.49, unit: "bag",  image: img("mm1") },
  { id: "s26", name: "Hershey's Milk Chocolate",   price: 1.99, unit: "each", image: img("hers1") },
  { id: "s27", name: "Ghirardelli Dark Chocolate", price: 4.99, unit: "bar",  image: img("ghi1") },
  { id: "s28", name: "Lindt Excellence 70%",       price: 3.99, unit: "bar",  image: img("lindt1") },
  { id: "s29", name: "Triscuit Rosemary & Olive",  price: 4.49, unit: "box",  image: img("tris1") },
  { id: "s30", name: "Wheat Thins Original",       price: 4.29, unit: "box",  image: img("wt1") },
  { id: "s31", name: "Ritz Crackers",              price: 3.99, unit: "box",  image: img("ritz1") },
  { id: "s32", name: "Goldfish Cheddar",           price: 3.49, unit: "bag",  image: img("gold1") },
  { id: "s33", name: "Planters Salted Cashews",    price: 6.99, unit: "jar",  image: img("plan1") },
  { id: "s34", name: "Blue Diamond Almonds",       price: 7.49, unit: "bag",  image: img("alm1") },
  { id: "s35", name: "Mixed Nuts Deluxe",          price: 8.99, unit: "can",  image: img("nut1") },
  { id: "s36", name: "Sunflower Seeds (David's)",  price: 2.99, unit: "bag",  image: img("sun1") },
  { id: "s37", name: "Pumpkin Seeds",              price: 4.99, unit: "bag",  image: img("pump1") },
  { id: "s38", name: "Trail Mix Deluxe",           price: 5.99, unit: "bag",  image: img("trail1") },
  { id: "s39", name: "Beef Jerky Original",        price: 7.99, unit: "bag",  image: img("jerk1") },
  { id: "s40", name: "Turkey Jerky Peppered",      price: 6.99, unit: "bag",  image: img("jerk2") },
  { id: "s41", name: "Fruit Roll-Ups",             price: 3.49, unit: "box",  image: img("fru1") },
  { id: "s42", name: "Gummy Bears (Haribo)",       price: 2.99, unit: "bag",  image: img("gum1") },
  { id: "s43", name: "Swedish Fish",               price: 2.49, unit: "bag",  image: img("swed1") },
];
export const dairy = [
  { id: "d1",  name: "Whole Milk (1 gal)",           price: 4.49, unit: "gallon",   image: img("milk1") },
  { id: "d2",  name: "2% Reduced Fat Milk",          price: 4.29, unit: "gallon",   image: img("milk2") },
  { id: "d3",  name: "Skim Milk",                    price: 3.99, unit: "gallon",   image: img("milk3") },
  { id: "d4",  name: "Organic Whole Milk",           price: 6.99, unit: "half-gal", image: img("omilk1") },
  { id: "d5",  name: "Oat Milk (Original)",          price: 5.49, unit: "half-gal", image: img("oat1") },
  { id: "d6",  name: "Almond Milk (Unsweetened)",    price: 4.99, unit: "half-gal", image: img("almond1") },
  { id: "d7",  name: "Soy Milk",                     price: 4.49, unit: "half-gal", image: img("soy1") },
  { id: "d8",  name: "Coconut Milk",                 price: 3.99, unit: "can",      image: img("cocm1") },
  { id: "d9",  name: "Heavy Whipping Cream",         price: 3.99, unit: "pint",     image: img("cream1") },
  { id: "d10", name: "Half & Half",                  price: 2.99, unit: "pint",     image: img("hh1") },
  { id: "d11", name: "Sour Cream",                   price: 2.49, unit: "16 oz",    image: img("sour1") },
  { id: "d12", name: "Greek Yogurt (Fage 0%)",       price: 5.99, unit: "17.6 oz",  image: img("gyog1") },
  { id: "d13", name: "Chobani Vanilla",              price: 1.49, unit: "5.3 oz",   image: img("chob1") },
  { id: "d14", name: "Siggi's Plain Skyr",           price: 2.49, unit: "5.3 oz",   image: img("sigi1") },
  { id: "d15", name: "Activia Strawberry",           price: 1.29, unit: "4 oz",     image: img("acti1") },
  { id: "d16", name: "Cream Cheese (Philadelphia)",  price: 3.99, unit: "8 oz",     image: img("cream2") },
  { id: "d17", name: "Brie Cheese (round)",          price: 6.99, unit: "each",     image: img("brie1") },
  { id: "d18", name: "Cheddar Cheese (sharp)",       price: 4.99, unit: "8 oz",     image: img("ched1") },
  { id: "d19", name: "Colby Jack Slices",            price: 3.99, unit: "8 oz",     image: img("colby1") },
  { id: "d20", name: "Mozzarella (fresh)",           price: 4.49, unit: "8 oz",     image: img("moz1") },
  { id: "d21", name: "Shredded Mozzarella",          price: 3.99, unit: "8 oz",     image: img("moz2") },
  { id: "d22", name: "Parmesan (grated)",            price: 5.49, unit: "8 oz",     image: img("parm1") },
  { id: "d23", name: "Gruyère Cheese",               price: 7.99, unit: "8 oz",     image: img("gruy1") },
  { id: "d24", name: "Feta Cheese",                  price: 4.99, unit: "8 oz",     image: img("feta1") },
  { id: "d25", name: "Goat Cheese (log)",            price: 5.99, unit: "4 oz",     image: img("goat1") },
  { id: "d26", name: "Ricotta Cheese",               price: 3.99, unit: "15 oz",    image: img("ric1") },
  { id: "d27", name: "Cottage Cheese (4%)",          price: 3.49, unit: "16 oz",    image: img("cott1") },
  { id: "d28", name: "Butter (salted)",              price: 5.49, unit: "lb",       image: img("butt2") },
  { id: "d29", name: "Butter (unsalted)",            price: 5.49, unit: "lb",       image: img("butt3") },
  { id: "d30", name: "Ghee (Organic Valley)",        price: 9.99, unit: "jar",      image: img("ghee1") },
  { id: "d31", name: "Eggs (large, 12-ct)",          price: 4.99, unit: "dozen",    image: img("egg1") },
  { id: "d32", name: "Eggs (large, 18-ct)",          price: 6.99, unit: "18-ct",    image: img("egg2") },
  { id: "d33", name: "Organic Eggs (12-ct)",         price: 7.49, unit: "dozen",    image: img("oegg1") },
  { id: "d34", name: "Egg Whites (carton)",          price: 4.49, unit: "32 oz",    image: img("ew1") },
  { id: "d35", name: "Whipped Cream (spray)",        price: 3.49, unit: "can",      image: img("whip1") },
  { id: "d36", name: "String Cheese",                price: 3.99, unit: "12-pk",    image: img("string1") },
  { id: "d37", name: "Babybel Mini Cheese",          price: 5.99, unit: "6-pk",     image: img("baby1") },
  { id: "d38", name: "Laughing Cow Wedges",          price: 4.49, unit: "8-pk",     image: img("laugh1") },
  { id: "d39", name: "Velveeta Slices",              price: 3.99, unit: "12-pk",    image: img("velv1") },
  { id: "d40", name: "Kefir (Plain)",                price: 4.99, unit: "32 oz",    image: img("kef1") },
  { id: "d41", name: "Probiotic Drink (Yakult)",     price: 5.49, unit: "5-pk",     image: img("yak1") },
];
export const beverages = [
  { id: "b1",  name: "Coca-Cola (12-pack)",          price: 7.99, unit: "12-pk",  image: img("coke1") },
  { id: "b2",  name: "Diet Coke (12-pack)",          price: 7.99, unit: "12-pk",  image: img("coke2") },
  { id: "b3",  name: "Coke Zero (12-pack)",          price: 7.99, unit: "12-pk",  image: img("coke3") },
  { id: "b4",  name: "Pepsi (12-pack)",              price: 7.49, unit: "12-pk",  image: img("pep4") },
  { id: "b5",  name: "Dr Pepper",                   price: 7.49, unit: "12-pk",  image: img("drp1") },
  { id: "b6",  name: "Sprite (12-pack)",             price: 7.49, unit: "12-pk",  image: img("sprite1") },
  { id: "b7",  name: "Mountain Dew (12-pack)",       price: 7.99, unit: "12-pk",  image: img("mtdew1") },
  { id: "b8",  name: "Canada Dry Ginger Ale",       price: 6.99, unit: "12-pk",  image: img("gale1") },
  { id: "b9",  name: "Sparkling Water (LaCroix)",   price: 6.49, unit: "12-pk",  image: img("lacr1") },
  { id: "b10", name: "Topo Chico Mineral Water",    price: 1.99, unit: "bottle", image: img("topo1") },
  { id: "b11", name: "Perrier Sparkling Water",     price: 1.79, unit: "bottle", image: img("perr1") },
  { id: "b12", name: "Aquafina Water (24-pk)",      price: 5.99, unit: "24-pk",  image: img("aqua1") },
  { id: "b13", name: "Dasani Water (24-pk)",        price: 5.99, unit: "24-pk",  image: img("das1") },
  { id: "b14", name: "Smart Water (1L)",            price: 2.49, unit: "bottle", image: img("smart1") },
  { id: "b15", name: "Gatorade Blue Bolt",          price: 1.99, unit: "bottle", image: img("gat1") },
  { id: "b16", name: "Gatorade Orange",             price: 1.99, unit: "bottle", image: img("gat2") },
  { id: "b17", name: "Powerade Mountain Berry",     price: 1.79, unit: "bottle", image: img("pow1") },
  { id: "b18", name: "Red Bull Original",           price: 3.49, unit: "8.4 oz", image: img("redb1") },
  { id: "b19", name: "Monster Energy Green",        price: 3.29, unit: "16 oz",  image: img("mon1") },
  { id: "b20", name: "Celsius Blue Razz",           price: 2.99, unit: "12 oz",  image: img("cel1") },
  { id: "b21", name: "Reign Total Body Fuel",       price: 2.99, unit: "16 oz",  image: img("reign1") },
  { id: "b22", name: "Tropicana Orange Juice",      price: 4.99, unit: "52 oz",  image: img("troj1") },
  { id: "b23", name: "Minute Maid Lemonade",        price: 3.49, unit: "52 oz",  image: img("mm2") },
  { id: "b24", name: "Apple Juice (Mott's)",        price: 3.99, unit: "64 oz",  image: img("aj1") },
  { id: "b25", name: "Ocean Spray Cranberry",       price: 4.29, unit: "64 oz",  image: img("oc1") },
  { id: "b26", name: "Welch's Grape Juice",         price: 4.49, unit: "64 oz",  image: img("wel1") },
  { id: "b27", name: "V8 Vegetable Juice",          price: 4.99, unit: "46 oz",  image: img("v8a1") },
  { id: "b28", name: "Naked Green Machine",         price: 4.49, unit: "15 oz",  image: img("nak1") },
  { id: "b29", name: "Bolthouse Farms Carrot",      price: 3.99, unit: "52 oz",  image: img("bolt1") },
  { id: "b30", name: "Lipton Iced Tea (12-pk)",     price: 7.49, unit: "12-pk",  image: img("lip1") },
  { id: "b31", name: "Arizona Green Tea",           price: 1.29, unit: "can",    image: img("ari1") },
  { id: "b32", name: "Snapple Peach Tea",           price: 2.29, unit: "bottle", image: img("snap1") },
  { id: "b33", name: "Pure Leaf Sweet Tea",         price: 3.49, unit: "bottle", image: img("pure1") },
  { id: "b34", name: "Tazo Chai Latte (concentrate)", price: 5.99, unit: "32 oz",image: img("tazo1") },
  { id: "b35", name: "Starbucks Cold Brew",         price: 4.99, unit: "11 oz",  image: img("star2") },
  { id: "b36", name: "Stok Cold Brew Black",        price: 3.99, unit: "bottle", image: img("stok1") },
  { id: "b37", name: "Califia Nitro Cold Brew",     price: 4.49, unit: "can",    image: img("cal2") },
  { id: "b38", name: "Kombucha GT's Original",      price: 3.99, unit: "16 oz",  image: img("kom1") },
  { id: "b39", name: "Health-Ade Pink Lady Apple",  price: 4.49, unit: "16 oz",  image: img("ha1") },
  { id: "b40", name: "Olipop Classic Grape",        price: 2.99, unit: "12 oz",  image: img("oli1") },
  { id: "b41", name: "Liquid Death Mountain Water", price: 1.99, unit: "can",    image: img("liq1") },
  { id: "b42", name: "Coconut Water (Vita Coco)",   price: 3.99, unit: "33 oz",  image: img("vit1") },
];
export const allProducts = [
  ...fruits.map(p => ({ ...p, category: "fruits" })),
  ...vegetables.map(p => ({ ...p, category: "vegetables" })),
  ...snacks.map(p => ({ ...p, category: "snacks" })),
  ...dairy.map(p => ({ ...p, category: "dairy" })),
  ...beverages.map(p => ({ ...p, category: "beverages" })),
];

export const categories = [
  {
    id: "fruits",
    name: "Fruits",
    emoji: "🍎",
    description: "Fresh seasonal fruits sourced daily",
    gradient: "from-red-400 to-orange-300",
    bgLight: "bg-red-50",
    textColor: "text-red-600",
    borderColor: "border-red-200",
    items: fruits,
  },
  {
    id: "vegetables",
    name: "Vegetables",
    emoji: "🥦",
    description: "Crisp, farm-fresh vegetables",
    gradient: "from-green-500 to-emerald-400",
    bgLight: "bg-green-50",
    textColor: "text-green-700",
    borderColor: "border-green-200",
    items: vegetables,
  },
  {
    id: "snacks",
    name: "Snacks",
    emoji: "🍿",
    description: "Chips, cookies, bars & more",
    gradient: "from-yellow-400 to-amber-300",
    bgLight: "bg-yellow-50",
    textColor: "text-yellow-700",
    borderColor: "border-yellow-200",
    items: snacks,
  },
  {
    id: "dairy",
    name: "Dairy",
    emoji: "🧀",
    description: "Milk, cheese, yogurt & eggs",
    gradient: "from-blue-400 to-sky-300",
    bgLight: "bg-blue-50",
    textColor: "text-blue-600",
    borderColor: "border-blue-200",
    items: dairy,
  },
  {
    id: "beverages",
    name: "Beverages",
    emoji: "🥤",
    description: "Juices, sodas, water & more",
    gradient: "from-purple-500 to-violet-400",
    bgLight: "bg-purple-50",
    textColor: "text-purple-700",
    borderColor: "border-purple-200",
    items: beverages,
  },
];

export default categories;
